#!/usr/bin/bash

# copying folder structure over to UniqueLigands directory
mkdir ~/research/Annulment/tmqmgunique;
cd ligandstmqmg;
find . -type d > ../dirs.txt;
cd ../tmqmgunique;
xargs mkdir -p < ../dirs.txt;

# For each subfolder in extracted ligand directory
for dir in ~/research/Annulment/ligandstmqmg/*/*; do 
    # Run openbabel duplicate checking 
    obabel $dir/*.mol2 -O $dir/U*.mol -m --unique | /dev/null 
    # Delete empty files generated by OBabel
    find $dir -type f -empty -print -delete;
    # move unique files over to corresponding directory in UniqueLigands folder
    file_path=$dir;
    suffix="${file_path##*/ligandstmqmg/}";
    mv $dir/U*mol /home/brendan/research/Annulment/tmqmgunique/$suffix;
done;







